/**
 * AI Action Executor helper for Lyria.
 * Performs deep validation, sanitization, and normalization of proposed AI actions.
 */

const ALLOWED_MODULES = ['tasks', 'finance', 'projects', 'rewards', 'learnings', 'experiments'];

/**
 * Normalizes input date to YYYY-MM-DD format.
 * Supports YYYY-MM-DD, DD/MM/YYYY, and ISO timestamp strings.
 */
export function normalizeDate(dStr) {
  if (!dStr) return '';
  const clean = String(dStr).trim();
  if (!clean) return '';
  
  // 1. Format YYYY-MM-DD
  const ymdRegex = /^\d{4}-\d{2}-\d{2}$/;
  if (ymdRegex.test(clean)) return clean;

  // 2. Format DD/MM/YYYY
  const dmyRegex = /^(\d{2})\/(\d{2})\/(\d{4})$/;
  const match = clean.match(dmyRegex);
  if (match) {
    return `${match[3]}-${match[2]}-${match[1]}`;
  }

  // 3. ISO timestamp (e.g. 2026-06-25T13:00:00Z)
  if (clean.includes('T')) {
    return clean.split('T')[0];
  }

  return '';
}

/**
 * Normalizes time strings to HH:mm.
 */
export function normalizeTime(tStr) {
  if (!tStr) return '';
  const clean = String(tStr).trim();
  if (!clean) return '';

  // Format HH:mm or HH:mm:ss
  const hmRegex = /^(\d{2}):(\d{2})(:\d{2})?$/;
  const match = clean.match(hmRegex);
  if (match) {
    return `${match[1]}:${match[2]}`;
  }

  return '';
}

/**
 * Validates and sanitizes a proposed AI create payload.
 * Normalizes English/invalid enums into supported Portuguese values or throws an error.
 * Strips auto-generated fields.
 */
export function validateAndSanitizeAction(module, payload) {
  if (!ALLOWED_MODULES.includes(module)) {
    throw new Error(`Módulo não suportado: "${module}".`);
  }

  if (!payload || typeof payload !== 'object') {
    throw new Error('O payload da ação é inválido ou vazio.');
  }

  // Strip auto-generated fields to prevent sync and ID collisions
  const cleanPayload = { ...payload };
  const autoGeneratedKeys = ['id', 'createdAt', 'created_at', 'updatedAt', 'updated_at', 'deletedAt', 'deleted_at', 'order', 'list_order'];
  autoGeneratedKeys.forEach(k => delete cleanPayload[k]);

  switch (module) {
    case 'tasks': {
      if (!cleanPayload.title || typeof cleanPayload.title !== 'string' || !cleanPayload.title.trim()) {
        throw new Error('O título da tarefa é obrigatório.');
      }

      // Priority normalization
      if (cleanPayload.priority) {
        const p = String(cleanPayload.priority).toLowerCase().trim();
        if (p === 'high' || p === 'alta') cleanPayload.priority = 'alta';
        else if (p === 'medium' || p === 'average' || p === 'média' || p === 'media') cleanPayload.priority = 'média';
        else if (p === 'low' || p === 'baixa') cleanPayload.priority = 'baixa';
        else {
          throw new Error(`Prioridade inválida da tarefa: "${cleanPayload.priority}". Use baixa, média ou alta.`);
        }
      } else {
        cleanPayload.priority = 'média';
      }

      // Status normalization
      if (cleanPayload.status) {
        const s = String(cleanPayload.status).toLowerCase().trim();
        if (s === 'todo' || s === 'pending' || s === 'pendente') cleanPayload.status = 'pendente';
        else if (s === 'in_progress' || s === 'active' || s === 'em_andamento' || s === 'em andamento') cleanPayload.status = 'em_andamento';
        else if (s === 'done' || s === 'completed' || s === 'concluída' || s === 'concluida') cleanPayload.status = 'concluída';
        else if (s === 'deleted' || s === 'excluída' || s === 'excluida') cleanPayload.status = 'excluída';
        else {
          throw new Error(`Status inválido da tarefa: "${cleanPayload.status}". Use pendente, em_andamento ou concluída.`);
        }
      } else {
        cleanPayload.status = 'pendente';
      }

      // Recurrence normalization
      if (cleanPayload.recurrence) {
        const r = String(cleanPayload.recurrence).toLowerCase().trim();
        if (r === 'única' || r === 'unica' || r === 'once' || r === 'single') cleanPayload.recurrence = 'única';
        else if (r === 'diária' || r === 'diaria' || r === 'daily') cleanPayload.recurrence = 'diária';
        else if (r === 'semanal' || r === 'weekly') cleanPayload.recurrence = 'semanal';
        else if (r === 'mensal' || r === 'monthly') cleanPayload.recurrence = 'mensal';
        else {
          throw new Error(`Recorrência inválida da tarefa: "${cleanPayload.recurrence}". Use única, diária, semanal ou mensal.`);
        }
      } else {
        cleanPayload.recurrence = 'única';
      }

      // Date & Time normalization
      if (cleanPayload.dueDate) {
        const d = normalizeDate(cleanPayload.dueDate);
        if (!d) throw new Error(`Data de vencimento inválida: "${cleanPayload.dueDate}". Use YYYY-MM-DD.`);
        cleanPayload.dueDate = d;
      } else {
        cleanPayload.dueDate = '';
      }

      if (cleanPayload.scheduledDate) {
        const d = normalizeDate(cleanPayload.scheduledDate);
        if (!d) throw new Error(`Data agendada inválida: "${cleanPayload.scheduledDate}". Use YYYY-MM-DD.`);
        cleanPayload.scheduledDate = d;
      } else {
        cleanPayload.scheduledDate = '';
      }

      if (cleanPayload.scheduledTime) {
        const t = normalizeTime(cleanPayload.scheduledTime);
        if (!t) throw new Error(`Hora agendada inválida: "${cleanPayload.scheduledTime}". Use HH:mm.`);
        cleanPayload.scheduledTime = t;
      } else {
        cleanPayload.scheduledTime = '';
      }

      if (cleanPayload.dueTime) {
        const t = normalizeTime(cleanPayload.dueTime);
        if (!t) throw new Error(`Hora de vencimento inválida: "${cleanPayload.dueTime}". Use HH:mm.`);
        cleanPayload.dueTime = t;
      } else {
        cleanPayload.dueTime = '';
      }

      cleanPayload.reminderEnabled = Boolean(cleanPayload.reminderEnabled);

      if (cleanPayload.reminderAt) {
        const d = new Date(cleanPayload.reminderAt);
        if (isNaN(d.getTime())) throw new Error(`Data/hora de lembrete inválida: "${cleanPayload.reminderAt}".`);
        cleanPayload.reminderAt = d.toISOString();
      } else {
        cleanPayload.reminderAt = '';
      }

      cleanPayload.timezone = String(cleanPayload.timezone || 'America/Sao_Paulo');

      // Category validation
      const validTaskCats = ['Marketing', 'Conteúdo', 'Produto', 'Operações', 'Estratégia', 'Pessoal', 'Outro'];
      if (cleanPayload.category) {
        const catTrimmed = String(cleanPayload.category).trim();
        const match = validTaskCats.find(c => c.toLowerCase() === catTrimmed.toLowerCase());
        cleanPayload.category = match || 'Outro';
      } else {
        cleanPayload.category = '';
      }

      break;
    }

    case 'finance': {
      // Type normalization
      if (!cleanPayload.type) {
        throw new Error('O tipo de lançamento financeiro é obrigatório.');
      }
      const t = String(cleanPayload.type).toLowerCase().trim();
      if (t === 'income' || t === 'entrada' || t === 'receita') {
        cleanPayload.type = 'entrada';
      } else if (t === 'expense' || t === 'saída' || t === 'saida' || t === 'despesa') {
        cleanPayload.type = 'saída';
      } else {
        throw new Error(`Tipo de lançamento financeiro inválido: "${cleanPayload.type}". Use entrada ou saída.`);
      }

      // Amount validation
      const amt = parseFloat(String(cleanPayload.amount || '0').replace(',', '.'));
      if (isNaN(amt) || amt <= 0) {
        throw new Error('O valor do lançamento financeiro deve ser um número positivo maior que zero.');
      }
      cleanPayload.amount = amt;

      // Date validation
      if (!cleanPayload.date) {
        throw new Error('A data do lançamento financeiro é obrigatória.');
      }
      const d = normalizeDate(cleanPayload.date);
      if (!d) {
        throw new Error(`Data inválida do lançamento financeiro: "${cleanPayload.date}". Use YYYY-MM-DD.`);
      }
      cleanPayload.date = d;

      // Category validation
      const incomeCategories = ['Vendas', 'Serviços', 'Investimentos', 'Outros'];
      const expenseCategories = ['Marketing', 'Ferramentas', 'Operações', 'Pessoal', 'Educação', 'Impostos', 'Transporte', 'Carro', 'Combustível', 'Alimentação', 'Mercado', 'Restaurante', 'Moradia', 'Contas', 'Saúde', 'Assinaturas', 'Lazer', 'Outros'];
      const validPool = cleanPayload.type === 'entrada' ? incomeCategories : expenseCategories;

      if (cleanPayload.category) {
        const catTrimmed = String(cleanPayload.category).trim();
        const match = validPool.find(c => c.toLowerCase() === catTrimmed.toLowerCase());
        cleanPayload.category = match || 'Outros';
      } else {
        cleanPayload.category = 'Outros';
      }

      // Expense Class validation (for expenses only)
      const expenseClasses = ['Essencial', 'Fixo', 'Variável', 'Estratégico', 'Investimento', 'Supérfluo'];
      if (cleanPayload.type === 'saída') {
        if (cleanPayload.expenseClass) {
          const ecTrimmed = String(cleanPayload.expenseClass).trim();
          const match = expenseClasses.find(c => c.toLowerCase() === ecTrimmed.toLowerCase());
          cleanPayload.expenseClass = match || 'Variável';
        } else {
          cleanPayload.expenseClass = 'Variável';
        }
      } else {
        cleanPayload.expenseClass = '';
      }

      // Source normalization
      const validSources = ['dropshipping', 'conteúdo', 'serviços', 'ferramentas', 'marketing', 'operações', 'pessoal', 'outro'];
      if (cleanPayload.source) {
        const srcTrimmed = String(cleanPayload.source).toLowerCase().trim();
        const match = validSources.find(s => s === srcTrimmed);
        cleanPayload.source = match || 'outro';
      } else {
        cleanPayload.source = '';
      }

      // Fill optional fields
      cleanPayload.subcategory = String(cleanPayload.subcategory || '');
      cleanPayload.notes = String(cleanPayload.notes || '');
      cleanPayload.originalDescription = String(cleanPayload.originalDescription || '');
      cleanPayload.sourceBank = String(cleanPayload.sourceBank || 'Importado');
      cleanPayload.accountName = String(cleanPayload.accountName || '');
      cleanPayload.reviewStatus = String(cleanPayload.reviewStatus || 'approved');
      cleanPayload.fixedCostId = cleanPayload.fixedCostId || null;
      cleanPayload.periodKey = String(cleanPayload.periodKey || cleanPayload.date.substring(0, 7));

      break;
    }

    case 'projects': {
      if (!cleanPayload.title || typeof cleanPayload.title !== 'string' || !cleanPayload.title.trim()) {
        throw new Error('O título do projeto é obrigatório.');
      }

      // Status normalization
      if (cleanPayload.status) {
        const s = String(cleanPayload.status).toLowerCase().trim();
        if (s === 'ativo' || s === 'active') cleanPayload.status = 'ativo';
        else if (s === 'pausado' || s === 'paused') cleanPayload.status = 'pausado';
        else if (s === 'concluído' || s === 'concluido' || s === 'completed' || s === 'done') cleanPayload.status = 'concluído';
        else {
          throw new Error(`Status do projeto inválido: "${cleanPayload.status}". Use ativo, pausado ou concluído.`);
        }
      } else {
        cleanPayload.status = 'ativo';
      }

      // Category validation
      const projectCats = ['Conteúdo', 'Negócios', 'Estudos', 'Produto'];
      if (cleanPayload.category) {
        const catTrimmed = String(cleanPayload.category).trim();
        const match = projectCats.find(c => c.toLowerCase() === catTrimmed.toLowerCase());
        cleanPayload.category = match || '';
      } else {
        cleanPayload.category = '';
      }

      // Date validation
      if (cleanPayload.startDate) {
        const d = normalizeDate(cleanPayload.startDate);
        if (!d) throw new Error(`Data de início do projeto inválida: "${cleanPayload.startDate}". Use YYYY-MM-DD.`);
        cleanPayload.startDate = d;
      } else {
        cleanPayload.startDate = new Date().toISOString().split('T')[0];
      }

      if (cleanPayload.targetDate) {
        const d = normalizeDate(cleanPayload.targetDate);
        if (!d) throw new Error(`Data-alvo do projeto inválida: "${cleanPayload.targetDate}". Use YYYY-MM-DD.`);
        cleanPayload.targetDate = d;
      } else {
        cleanPayload.targetDate = '';
      }

      if (cleanPayload.completedAt) {
        const d = normalizeDate(cleanPayload.completedAt);
        if (!d) throw new Error(`Data de conclusão do projeto inválida: "${cleanPayload.completedAt}". Use YYYY-MM-DD.`);
        cleanPayload.completedAt = d;
      } else {
        cleanPayload.completedAt = '';
      }

      cleanPayload.description = String(cleanPayload.description || '');
      cleanPayload.subtasks = Array.isArray(cleanPayload.subtasks) ? cleanPayload.subtasks.map(s => ({
        id: s.id || crypto.randomUUID(),
        title: String(s.title || 'Subtarefa'),
        completed: Boolean(s.completed),
        order: typeof s.order === 'number' ? s.order : 0
      })) : [];

      break;
    }

    case 'rewards': {
      if (!cleanPayload.title || typeof cleanPayload.title !== 'string' || !cleanPayload.title.trim()) {
        throw new Error('O título da recompensa é obrigatório.');
      }

      // Category validation
      const rewardCats = ['Trabalho', 'Financeiro', 'Saúde', 'Casa', 'Estudos', 'Lazer', 'Pessoal', 'Outro'];
      if (cleanPayload.category) {
        const catTrimmed = String(cleanPayload.category).trim();
        const match = rewardCats.find(c => c.toLowerCase() === catTrimmed.toLowerCase());
        cleanPayload.category = match || 'Outro';
      } else {
        cleanPayload.category = 'Outro';
      }

      // Priority normalization
      if (cleanPayload.priority) {
        const p = String(cleanPayload.priority).toLowerCase().trim();
        if (p === 'high' || p === 'alta') cleanPayload.priority = 'alta';
        else if (p === 'medium' || p === 'average' || p === 'média' || p === 'media') cleanPayload.priority = 'média';
        else if (p === 'low' || p === 'baixa') cleanPayload.priority = 'baixa';
        else {
          throw new Error(`Prioridade da recompensa inválida: "${cleanPayload.priority}". Use baixa, média ou alta.`);
        }
      } else {
        cleanPayload.priority = 'média';
      }

      // Status normalization
      if (cleanPayload.status) {
        const s = String(cleanPayload.status).toLowerCase().trim();
        if (s === 'em_andamento' || s === 'em andamento' || s === 'running') cleanPayload.status = 'em_andamento';
        else if (s === 'desbloqueada' || s === 'unlocked') cleanPayload.status = 'desbloqueada';
        else if (s === 'resgatada' || s === 'redeemed') cleanPayload.status = 'resgatada';
        else {
          throw new Error(`Status da recompensa inválido: "${cleanPayload.status}". Use em_andamento, desbloqueada ou resgatada.`);
        }
      } else {
        cleanPayload.status = 'em_andamento';
      }

      cleanPayload.estimatedValue = cleanPayload.estimatedValue ? parseFloat(String(cleanPayload.estimatedValue).replace(',', '.')) || 0 : 0;
      
      cleanPayload.deadline = normalizeDate(cleanPayload.deadline) || '';
      cleanPayload.redeemAvailableDate = normalizeDate(cleanPayload.redeemAvailableDate) || '';
      cleanPayload.redeemedAt = normalizeDate(cleanPayload.redeemedAt) || '';
      cleanPayload.archivedAt = normalizeDate(cleanPayload.archivedAt) || '';
      cleanPayload.notes = String(cleanPayload.notes || '');
      cleanPayload.showOnDashboard = Boolean(cleanPayload.showOnDashboard);

      cleanPayload.financialTargetAmount = cleanPayload.financialTargetAmount ? parseFloat(String(cleanPayload.financialTargetAmount).replace(',', '.')) || null : null;
      cleanPayload.financialCurrentAmount = cleanPayload.financialCurrentAmount ? parseFloat(String(cleanPayload.financialCurrentAmount).replace(',', '.')) || null : null;

      cleanPayload.conditions = Array.isArray(cleanPayload.conditions) ? cleanPayload.conditions.map(c => ({
        id: c.id || crypto.randomUUID(),
        text: String(c.text || ''),
        completed: Boolean(c.completed),
        completedAt: normalizeDate(c.completedAt) || null
      })) : [];

      break;
    }

    case 'learnings': {
      if (!cleanPayload.content || typeof cleanPayload.content !== 'string' || !cleanPayload.content.trim()) {
        throw new Error('O conteúdo do aprendizado é obrigatório.');
      }
      cleanPayload.source = String(cleanPayload.source || '');
      cleanPayload.tags = Array.isArray(cleanPayload.tags) ? cleanPayload.tags.map(t => String(t).trim().toLowerCase()) : [];
      cleanPayload.isFavorite = Boolean(cleanPayload.isFavorite);
      cleanPayload.date = normalizeDate(cleanPayload.date) || new Date().toISOString().split('T')[0];
      break;
    }

    case 'experiments': {
      if (!cleanPayload.title || typeof cleanPayload.title !== 'string' || !cleanPayload.title.trim()) {
        throw new Error('O título do experimento é obrigatório.');
      }

      // Category validation
      const expCats = ['ads', 'conteúdo', 'negócio', 'operacional', 'produtividade', 'estratégia', 'outro'];
      if (!cleanPayload.category || typeof cleanPayload.category !== 'string' || !cleanPayload.category.trim()) {
        throw new Error('A categoria do experimento é obrigatória.');
      } else {
        const cat = cleanPayload.category.toLowerCase().trim();
        const match = expCats.find(c => c === cat);
        if (!match) {
          throw new Error(`Categoria de experimento inválida: "${cleanPayload.category}". Escolha entre: ${expCats.join(', ')}.`);
        }
        cleanPayload.category = match;
      }

      // Repeat normalization
      if (cleanPayload.repeatThis) {
        const r = String(cleanPayload.repeatThis).toLowerCase().trim();
        if (r === 'sim' || r === 'yes' || r === 'true') cleanPayload.repeatThis = 'sim';
        else if (r === 'não' || r === 'nao' || r === 'no' || r === 'false') cleanPayload.repeatThis = 'não';
        else {
          throw new Error(`Valor de repetição inválido: "${cleanPayload.repeatThis}". Use "sim" ou "não".`);
        }
      } else {
        cleanPayload.repeatThis = 'sim';
      }

      cleanPayload.context = String(cleanPayload.context || '');
      cleanPayload.whatWasTested = String(cleanPayload.whatWasTested || '');
      cleanPayload.result = String(cleanPayload.result || '');
      cleanPayload.mainError = String(cleanPayload.mainError || '');
      cleanPayload.lessonLearned = String(cleanPayload.lessonLearned || '');
      cleanPayload.notes = String(cleanPayload.notes || '');
      cleanPayload.date = normalizeDate(cleanPayload.date) || new Date().toISOString().split('T')[0];
      cleanPayload.tags = Array.isArray(cleanPayload.tags) ? cleanPayload.tags.map(t => String(t).trim().toLowerCase()) : [];

      break;
    }
  }

  return cleanPayload;
}
